{
 "title": "Device Health",
 "description": "Overview of a device health status. It includes resources, interfaces and BGP information if available.",
 "tags": [ "network" ],
 "time": { "from": "now-4h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(device_uptime,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device Details",
   "type": "table",
   "description": "Device Detailed Information from Nautobot",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "devices",
     "endTimePath": "endTime",
     "queryText": "query {\n  devices(name: \"$device\") {\n    id\n    name\n    role {\n      name\n    }\n    device_type {\n      manufacturer {\n        name\n      }\n      model\n    }\n    status {\n      name\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "description": "Device overall state from a ping result",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_result_code{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Device Uptime based on SNMP metric",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_uptime{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Mem",
   "type": "gauge",
   "description": "Overall Memory average usage for the device",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memory_used{device=\"$device\"} * 100) / (memory_used{device=\"$device\"} + memory_available{device=\"$device\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg CPU",
   "type": "gauge",
   "description": "Overall CPU average usage for the device",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cpu_used{device=\"$device\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Average Latency of a device",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_average_response_ms{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU & Mem Usage (Avg)",
   "type": "timeseries",
   "description": "CPU and Memory usage in average for available cores on the device",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cpu_used{device=\"$device\"}[2m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "avg((memory_used{device=\"$device\"} * 100) / (memory_used{device=\"$device\"} + memory_available{device=\"$device\"}))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "stat",
   "description": "Total Inbound + Outbound traffic on a device",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(interface_in_octets{device=\"$device\"}[2m]) * 8 + rate(interface_out_octets{device=\"$device\"}[2m]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Interfaces Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Interfaces State",
   "type": "state-timeline",
   "description": "Interfaces State change over time",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "interface_oper_status{device=\"$device\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Total Interfaces Down",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(interface_oper_status{device=\"$device\"} == 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interfaces Detail",
   "type": "table",
   "description": "Interfaces Detail table collected from the device",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(interface_in_octets{device=\"$device\"}[2m]) * 8 + rate(interface_out_octets{device=\"$device\"}[2m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "interface_oper_status{device=\"$device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "interface_admin_status{device=\"$device\"}",
     "legendFormat": "__auto"
    },
    {
     "constant": 6.5,
     "dataPath": "interfaces",
     "endTimePath": "endTime",
     "queryText": "{\n  interfaces(device: \"$device\", label__n: \"loopback\") {\n    name\n    label\n    sot_device: device {\n      name\n    }\n    sot_intended_state: status {\n      name\n    }\n  }\n}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Total Interfaces Up",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(interface_oper_status{device=\"$device\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "stat",
   "description": "Average Inbound Traffic",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(interface_in_octets{device=\"$device\"}[2m]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic over time",
   "type": "timeseries",
   "description": "Interfaces Traffic over time (negative values are outbound traffic)",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(interface_in_octets{device=\"$device\"}[2m]) * 8)",
     "legendFormat": "Sum(Inbound)"
    },
    {
     "expr": "sum(rate(interface_out_octets{device=\"$device\"}[2m]) * 8) * -1",
     "legendFormat": "Sum(Outbound)"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "stat",
   "description": "Average Outbound Traffic",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(interface_out_octets{device=\"$device\"}[2m]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP & Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prefixes Accepted",
     "type": "stat",
     "description": "Total BGP Prefixes Accepted",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bgp_prefixes_accepted{device=\"$device\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BGP States",
     "type": "state-timeline",
     "description": "BGP State change over time",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "bgp_neighbor_state{device=\"$device\"}",
       "legendFormat": "(ASN: {{neighbor_asn}}) - {{neighbor}}"
      }
     ]
    },
    {
     "title": "Device Logs",
     "type": "logs",
     "description": "Device Logs Panel",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{device=\"$device\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}